# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "" # repository name
# url: "http://sunrisechurch.us" # Production host
# url: "http://whaleen.github.io/sunrisechurch.us/" # Development host
url: "http://127.0.0.1:4000" # Either custom domain or http://GithubUsername.github.io

# Podcast Feed Settings
title:          "Sunrise Church" # name of your podcast
email:          bill@sunrisechurch.us # CHANGE
description:    "A Podcast of Sermons from Sunrise Church, a Christian Reformed Church in McMinnville OR pastored by Bill Wilton." # CHANGE
subtitle:       "Weekly Sermons from Pastor Wilton" # CHANGE
lang:           en-us
author:         Bill Wilton # CHANGE
copyright:      "&#x2117; &amp; &#xA9; 2016"


# Outputting
permalink: /:title/

# Build settings
markdown: kramdown
timezone: America/New_York #CHANGE

# Basic

# Navigation
nav:
  - name:           "About"
    href:           "/microcast/about" # CHANGE "microcast" to match your repository
  - name:           "Feed"
    href:           "/podcast.rss" # CHANGE "microcast" to match your repository
  - name:           "iTunes"
    href:           "https://itunes.apple.com/us/podcast/driftwood/id1080157963" #CHANGE
  - name:           "Overcast"
    href:           "https://overcast.fm/itunes1080157963/driftwood" # CHANGE

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
