# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "" # repository name

# url: "http://sunrisechurch.us" # Production host
url: "http://whaleen.github.io/sunrisechurch.us" # Development host
# url: "http://127.0.0.1:4000" # Either custom domain or http://GithubUsername.github.io

# Podcast Feed Settings
title:          "Sunrise Church" # name of your podcast
email:          pastorbill@sunrisechurch.us # CHANGE
description:    "A Podcast of Sermons from Sunrise Church, a Christian Reformed Church in McMinnville OR pastored by Bill Wilton." # CHANGE
subtitle:       "Weekly Sermons from Pastor Wilton" # CHANGE
lang:           en-us
author:         Bill Wilton # CHANGE
copyright:      "&#x2117; &amp; &#xA9; 2016"


# Outputting
permalink: /:title/

# Build settings
markdown: kramdown
timezone: America/New_York #CHANGE

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"





# Prose.io configuration

prose:
  rooturl: '_posts'
  siteurl: 'http://whaleen.github.io/sunrisechurch.us '
  relativeLinks: 'http://whaleen.github.io/sunrisechurch.us/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "section"
        field:
          element: "multiselect"
          label: "Section"
          placeholder: "Choose Section"
          options:
            - name: "Listen"
              value: "listen"
            - name: "Read"
              value: "read"
      - name: "category"
        field:
          element: "multiselect"
          label: "Category"
          placeholder: "Choose Category"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
    _posts/sermons:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
